### ISSUE TITLE
Executing the node group from a python script

### ISSUE THREAD

**Issue by gerroon** [AIGODLIKE/ComfyUI-BlenderAI-node#104]
Hi

I can normally execute node groups like
`bpy.data.node_groups["animation nodes"].execute()`

This node group does not seem to have an execute function. I need to run the execution from a script in Blender. How do I do that?

thanks

**Comment by KarryCharon** [comment]
> Hi
> 
> I can normally execute node groups like `bpy.data.node_groups["animation nodes"].execute()`
> 
> This node group does not seem to have an execute function. I need to run the execution from a script in Blender. How do I do that?
> 
> thanks

Added! See latest dev branch
