### ISSUE TITLE
Input Image node missing "未定义的节点 > 输入图像"

### ISSUE THREAD

**Issue by blendlet** [AIGODLIKE/ComfyUI-BlenderAI-node#109]
When trying to add an Input Image node, I get these lines in the Blender Info Log.
```
bpy.ops.node.add_node(use_transform=True, type="输入图像")
bpy.ops.sdn.node_search(item='输入图像')
未定义的节点 > 输入图像
```
This may also be related to the issue described here https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/discussions/103

**Comment by blendlet** [comment]
Fixed by manually uninstalling and reinstalling the cusyom node ComfyUI-CUP with ComfyUI Manager.

**Comment by D-a-r-n-o-l-d** [comment]
worked for me too thanks!
