### ISSUE TITLE
diff_object_info.json

### ISSUE THREAD

**Issue by tetsuoo-online** [AIGODLIKE/ComfyUI-BlenderAI-node#111]
This file 'diff_object_info.json' keeps updating itself, the size change all the time even when Blender is not open and I'm not using the addon in any way at the moment, what is this ??

**Comment by KarryCharon** [comment]
`diff_object_info.json` is used by Blender's node dynamic updating(caused by comfyui). Our service registed in comfyui will flush diff node info into `diff_object_info.json` file while some nodes changed.
