### ISSUE TITLE
Can't use because half the nodes don't have input and output

### ISSUE THREAD

**Issue by TheCalibrator** [AIGODLIKE/ComfyUI-BlenderAI-node#112]
![2024-07-07_16-28](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/98053058/c63c8841-91bc-411c-a0ce-f48286335070)
I fixed Input Image by reinstalling some module thingy in ComfyUI, but then to fix the preview node I had to reinstall the comfyUI Addon, now the Input Image node is broken again. Also the Ksampler node... What do I do now?

**Comment by KarryCharon** [comment]
> ![2024-07-07_16-28](https://private-user-images.githubusercontent.com/98053058/346342069-c63c8841-91bc-411c-a0ce-f48286335070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzM5OTcsIm5iZiI6MTcyMDc3MzY5NywicGF0aCI6Ii85ODA1MzA1OC8zNDYzNDIwNjktYzYzYzg4NDEtOTFiYy00MTFjLWEwY2UtZjQ4Mjg2MzM1MDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA4NDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyOTA2M2M3MzU0NzRjNmQ2ZWQ0ZGY1NTFhODQ4YjU1NjI3MTlkMzFlOGJjYWE5OTk5MjI5NTllNmJmNDQ2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UEf3K_Oa5BB8KGV55pEjbiEwYpPU_tQCHix9SzwR-Ck) I fixed Input Image by reinstalling some module thingy in ComfyUI, but then to fix the preview node I had to reinstall the comfyUI Addon, now the Input Image node is broken again. Also the Ksampler node... What do I do now?

Is there any error log in blender system console?

**Comment by TheCalibrator** [comment]
I'm lost... I try this again to find the errors and it works. I suppose you can close this unless you want me to do something, but yeah it seems to work now.
