### ISSUE TITLE
SDN-ERR

### ISSUE THREAD

**Issue by AonoZan** [AIGODLIKE/ComfyUI-BlenderAI-node#120]
TypeError: must be real number, not list
[SDN-ERR]: Failed to register <class 'BlenderAI_Node.SDNode.nodes.CreateShapeImageOnPath'> -> bpy_struct "CreateShapeImageOnPath" registration error: 'size_multiplier' FloatProperty could not register (see previous error)
TypeError: must be real number, not list
[SDN-ERR]: Failed to register <class 'BlenderAI_Node.SDNode.nodes.CreateShapeMaskOnPath'> -> bpy_struct "CreateShapeMaskOnPath" registration error: 'size_multiplier' FloatProperty could not register (see previous error)
TypeError: must be real number, not list
[SDN-ERR]: Failed to register <class 'BlenderAI_Node.SDNode.nodes.CreateTextOnPath'> -> bpy_struct "CreateTextOnPath" registration error: 'size_multiplier' FloatProperty could not register (see previous error)
TypeError: must be real number, not list
[SDN-ERR]: Failed to register <class 'BlenderAI_Node.SDNode.nodes.PlotCoordinates'> -> bpy_struct "PlotCoordinates" registration error: 'size_multiplier' FloatProperty could not register (see previous error)
TypeError: must be real number, not list
[SDN-ERR]: Failed to register <class 'BlenderAI_Node.SDNode.nodes.GLIGENTextBoxApplyBatchCoords'> -> bpy_struct "GLIGENTextBoxApplyBatchCoords" registration error: 'size_multiplier' FloatProperty could not register (see previous error)
TypeError: must be real number, not list
[SDN-ERR]: Failed to register <class 'BlenderAI_Node.SDNode.nodes.CreateInstanceDiffusionTracking'> -> bpy_struct "CreateInstanceDiffusionTracking" registration error: 'size_multiplier' FloatProperty could not register (see previous error)

**Comment by KarryCharon** [comment]
@AonoZan This err log mean some nodes parsing error. Not impact others nodes that parsed.
