### ISSUE TITLE
workflow explanation

### ISSUE THREAD

**Issue by ekswathi** [AIGODLIKE/ComfyUI-BlenderAI-node#130]
please can someone explain the workflow of the fist video of the Readme. (i mean texture painting on 3d object)

**Comment by DorotaLuna** [comment]
its just text to image with depth and normal controlnet
depth and normal images comes up by compositing
generate textures from different view then merge them together
the merge part uses some algorithm that can make a full texture with different views

![image](https://github.com/user-attachments/assets/30605935-8d6f-428c-8e49-76c0566e82c4)

**Comment by ekswathi** [comment]
thank you for quick answer. the merge part algorithm is what i am interested bro. because when i project the result and bake it always give me black edges. but yours give smooth transition
