### ISSUE TITLE
malware is detected

### ISSUE THREAD

**Issue by mill101** [AIGODLIKE/ComfyUI-BlenderAI-node#135]
Hello,

A Trojan horse is detected under this directory. 
How should I deal with it?

ComfyUI-BlenderAI-node-main/External/SDN-1.1/lualib/luahook.dll - Win64/GenKryptik_AGen.UK
ComfyUI-BlenderAI-node-main/External/listen/hook.dll - Win64/GenKryptik_AGen.UK

Thanks.

**Comment by KarryCharon** [comment]
If you download addon from this repo url, or clone from this url, Just trust it's safe!
