### ISSUE TITLE
ComfyUI not launching, stuck at loading ComfyUI-Manager

### ISSUE THREAD

**Issue by YannJun** [AIGODLIKE/ComfyUI-BlenderAI-node#15]
After installed the v1.2.3 plugin and cup.py created ComfyUI, ComfyUI is not launching anymore (via Blender or via the .bat launcher file or via command line with main.py ). Remove cup.py make the launching possible again.
(ComfyUI lastest Windows Portable verison )

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/15173390/ab3c5773-14b4-4d75-a956-d640abe7f923)

Any thought?

**Comment by YannJun** [comment]
Removing ComfyUI-Manger while keeping cup.py also make the server start successful. But all the nodes remain grayed-out and no node tress can be prawned (no effect when creating).

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/15173390/c5828552-2894-428c-bdbb-8cd444647862)

**Comment by KarryCharon** [comment]
@YannJun 灰色的原因是没新建节点树, 需要点击 你图片里 上方中间的 New 按钮 新建一个节点树

**Comment by KarryCharon** [comment]
@YannJun 最新版修复了 ComfyUI-Manager卡住的问题
