### ISSUE TITLE
Blender 3.6 comfyui error

### ISSUE THREAD

**Issue by kakachiex2** [AIGODLIKE/ComfyUI-BlenderAI-node#22]
I' get this error when trying to activate ComfyUI addon this happen after update to develop branch
the main load the addon but nothing happen when trying to load checkpoint or lora model don't appear in the node.
![Blender comfyui bug](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/7a8e0559-5100-48f1-889c-2a72658d650f)

**Comment by Yorha4D** [comment]
> I' get this error when trying to activate ComfyUI addon this happen after update to develop branch我在尝试激活ComfyUI插件时收到此错误，这发生在更新到开发分支后 the main load the addon but nothing happen when trying to load checkpoint or lora model don't appear in the node.主加载插件，但在尝试加载检查点或 LoRa 模型时没有任何反应不会出现在节点中. ![Blender comfyui bug](https://user-images.githubusercontent.com/1762112/266797502-7a8e0559-5100-48f1-889c-2a72658d650f.png)

@kakachiex2 This is because some nodes used non-standard enumeration data and have already been processed. Please update the development branch's 1.2.8
