### ISSUE TITLE
Another Bug Appear

### ISSUE THREAD

**Issue by kakachiex2** [AIGODLIKE/ComfyUI-BlenderAI-node#23]
Still, I' can't use the Addon it Crash Blender and wen it loads after running the engine blender crash, I test it with B-3.5.1 and B-3.6.2
First error.
![Screenshot 2023-09-10 212959](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/242049d4-af99-475b-a0fa-8c4ca41ab2ea)
and second after click again
![Screenshot 2023-09-10 213032](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/dd019883-a124-4345-8863-2c307b72e8d5)

**Comment by Yorha4D** [comment]
> Still, I' can't use the Addon it Crash Blender and wen it loads after running the engine blender crash, I test it with B-3.5.1 and B-3.6.2 First error. ![Screenshot 2023-09-10 212959](https://user-images.githubusercontent.com/1762112/266886169-242049d4-af99-475b-a0fa-8c4ca41ab2ea.png) and second after click again ![Screenshot 2023-09-10 213032](https://user-images.githubusercontent.com/1762112/266886268-dd019883-a124-4345-8863-2c307b72e8d5.png)

@kakachiex2 This is because some nodes used non-standard enumeration data and have already been processed. Please update the development branch's 1.2.8
