### ISSUE TITLE
Another bug after getting the addon to load

### ISSUE THREAD

**Issue by kakachiex2** [AIGODLIKE/ComfyUI-BlenderAI-node#24]
I get the addon to load but after running the engine give me this error 
![Screenshot 2023-09-11 074230](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/7ba95aa2-548a-401a-be12-0d38b36528e7)
Error wen running the engine button "ON"
![Screenshot 2023-09-11 074348](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/44698d25-55ec-4537-b1be-429b0a696135)

**Comment by kakachiex2** [comment]
After this error the addon panel disappear and I can't reload it never again I' have to remove the addon manually > load Blender > close Blender > install the addon from main > switch to develop branch > update and them it works.

**Comment by Yorha4D** [comment]
> After this error the addon panel disappear and I can't reload it never again I' have to remove the addon manually > load Blender > close Blender > install the addon from main > switch to develop branch > update and them it works.在此错误之后，插件面板消失了，我再也无法重新加载它，我必须手动删除插件>加载Blender>关闭Blender>从主>开关安装插件以开发分支>更新，并且可以正常工作。

@kakachiex2 Yes, because some custom nodes have recently used non-standard enumeration data
