### ISSUE TITLE
Efficiency node suite bug

### ISSUE THREAD

**Issue by kakachiex2** [AIGODLIKE/ComfyUI-BlenderAI-node#26]
I don't know if this is a bug or limitation but this is how the efficiency node suite lora stacker behave in Blender, it supposed to add stacker and remove it but it adds all wens place it.]
![Screenshot 2023-09-20 131238](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/605ffee5-0b99-4850-bd85-69231bffadc9)

**Comment by kakachiex2** [comment]
And know I' can use it thank you very much for the fix...😁😁😁

**Comment by cx1132692358** [comment]
@kakachiex2 I'll check the problem

**Comment by Yorha4D** [comment]
@kakachiex2 Although this may seem crazy, it remains consistent in Blender's UI and Web. Perhaps a suggestion needs to be made to the efficiency node suite project
