### ISSUE TITLE
提示“添加任务”，然后无法运行了~ 

### ISSUE THREAD

**Issue by i-iooi-i** [AIGODLIKE/ComfyUI-BlenderAI-node#36]
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/183d228f-e3cf-4664-ba7d-43f856fc37db)
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/5c7c0c59-1b4e-467e-87f8-8d58bbfe7794)
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/3a5458e1-6750-4b9e-8346-4b7714e9cbf1)
只能生图一次
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/a8f23083-a710-4551-ae2c-53a36b1d8393)
再点击 “运行节点树”，就只有 “添加任务” 的提示了，没有任何生图结果了。
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/f8378125-43d4-497b-9b73-2417b4530859)
重装了Blender，重装了插件，更改Blender语言为英文，都没有作用。
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/6004a8aa-e438-4d9f-ae41-65cbe63f8203)
下载安装的是 https://github.com/comfyanonymous/ComfyUI ，
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/7ad55e87-c6ea-4cdc-9c51-777ef443d428)
测试了一下，ComfyUI在浏览器里生成图像没有任何问题。

**Comment by KarryCharon** [comment]
@i-iooi-i  试试 develop 最新版是1.3.2

**Comment by KarryCharon** [comment]
@i-iooi-i  还是不行的话, 可以加官方群606817483 我远程帮你看看

**Comment by i-iooi-i** [comment]
> @i-iooi-i 还是不行的话, 可以加官方群606817483 我远程帮你看看

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1827701/2fbeb4e5-b1c8-45a5-a8cb-d6f54bcd9c8a)
用了 develop 版本完美完美运行了~~ 感谢大佬🫡🫡  
我还以为是我电脑或者插件的问题，折腾了两个小时~~😂😂😂
好的，我晚点加下群，后续有啥问题还要麻烦请教了。♥️

**Comment by KarryCharon** [comment]
@i-iooi-i 好的
