### ISSUE TITLE
Preview images are not displayed in addon panel

### ISSUE THREAD

**Issue by KoreTeknology** [AIGODLIKE/ComfyUI-BlenderAI-node#38]
Both presets and groups are not displayed due to its file format (the image is not visiible in windows image preview application too)
>>> PC windows 11 , last 3.6.5 Blender release

**Comment by KarryCharon** [comment]
@KoreTeknology maybe git clone is needed, download the zip directly will miss the image data

**Comment by KoreTeknology** [comment]
ok, thanks. 
Could be nice to have an  image load field in the save preset windows ;)
