### ISSUE TITLE
IMB_ibImageFromMemory: unknown file-format

### ISSUE THREAD

**Issue by LucasGuzman3D** [AIGODLIKE/ComfyUI-BlenderAI-node#42]
After working all day on a blender file, when I closed it and opened it again, it wouldn't open.
Then I downloaded the develop branch, and that allowed me to open the file. Once I clicked on "Launch/Connect ComfyUI", the console would throw all these errors and freeze blender completely:

`IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\presets\06τ╗¥σ¡ªσÑÑΣ╣ë\Σ╕ëσêåσ╜Æσàâµ░ö.json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\01σ¢╛σâÅΘóäΦºê.json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\02σ¢╛σâÅσ»╝σàÑ.json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\03σ¢╛σâÅΣ┐¥σ¡ÿ.json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\04σ¢╛σâÅµö╛σñº(σÅ»Φ«╛σ░║σ»╕).json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\05σ¢╛σâÅµö╛σñº(µ£ÇσñºσÇ╝).json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\06Φ╢àσêåΣ┐«σñì.json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\07σÅîσÉæµÅÉτñ║Φ»ì.json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\08τ⌐╢µ₧üΘ½ÿµ╕àΣ┐«σñì.json.jpg)
IMB_ibImageFromMemory: unknown file-format (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\groups\σ╕╕τö¿τ╗äΣ╗╢\09µÅÉτñ║Φ»ìµè╜σìí.json.jpg)`

I am able to open a new file of Blender and run ComfyUI and it works well. But it just wont let me continue with that saved file. 
What happened along the way, and how could I avoid it next time?

**Comment by KarryCharon** [comment]
@LucasGuzman3D Are you downloaded the zip file directly? Maybe you can use the git clone for downloading
