### ISSUE TITLE
Blender freezes completely when Launch/Connect ComfyUI on saved blender file.

### ISSUE THREAD

**Issue by LucasGuzman3D** [AIGODLIKE/ComfyUI-BlenderAI-node#43]
When I opened a Blend file I have been using yesterday all day, Blender would freeze completely. No logs, just "opening file".
I deactivated ComfyUI-BlenderAI-node, and then I was able to open the file again. 
If then I go to launch the addon, Blender would freeze completely again. No crash, just freeze.

I updated to develop branch by cloning the repo. Now I can open the file, addon is disabled, I enable it, then when I click Launch, same thing, Blender freezes.

When opening the file, I get these errors:

`blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
blenderkit addon: Running background update callback
blenderkit addon: Attempted popup prompt
blenderkit INFO: Global dir permissions are OK. [08:22:55.344, utils.py:1295]
blenderkit INFO: Dependencies are available [08:22:55.426, dependencies.py:111]
blenderkit INFO: Daemon is running on port 62485! [08:22:55.607, timer.py:86]
blenderkit addon: Running the install popup handler.
Read blend: "E:\Dropbox\_PROJECTS2023\SwipeBack\Freebets\_BLENDER\ComfyUI_Archipelagos_A002.blend"
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'`

That's the only peculiar thing I see on the log. Sadly I cant find any more info on what happens when Blender freezes because I see nothing on the logs, it just freezes and I have to kill the process.

You can check the file here:
https://www.dropbox.com/scl/fi/0zfbvsel3or2e3gm3hbe8/ComfyUI_Archipelagos_A002_crash.blend?rlkey=fqzrfdxq8x4s5lgwbg9x3kw6x&dl=0

**Comment by KarryCharon** [comment]
@LucasGuzman3D Unknown reason, I checked this file and found it can be opening at my windows pc but not my mac pc.
The other hand, this blend file can be appended into a new project. So may be you can appending it or try my commit one(see below).
[ComfyUI_Archipelagos_A003_crash.blend.zip](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/files/13236818/ComfyUI_Archipelagos_A003_crash.blend.zip)

**Comment by KarryCharon** [comment]
@LucasGuzman3D If both of those are not working, maybe you should start from emty project :)

**Comment by KarryCharon** [comment]
@LucasGuzman3D I also tried to launch comfyUI and confirmed that it would get stuck. This bug may take some time

**Comment by KarryCharon** [comment]
@LucasGuzman3D Fixed, have a try :)
