### ISSUE TITLE
 LCM Realtime Viewport Generation 

### ISSUE THREAD

**Issue by saphtea** [AIGODLIKE/ComfyUI-BlenderAI-node#44]
I'm curious if it could ever be on the map to make close to realtime generation in viewport happen with lcm! https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7

**Comment by KarryCharon** [comment]
@saphtea You mean this https://github.com/0xbitches/ComfyUI-LCM ?

**Comment by saphtea** [comment]
Nope! Not LCM support itself, but the ability to preview LCM generation in the viewport would be nice, like a rendered view.

I imagine it'd work out well if it waited for the samples to complete in the chosen rendering engine, sent that through LCM or whatever your comfyui node setup is, then render that final generation in viewport.

**Comment by KarryCharon** [comment]
@saphtea Unfortunately we are now working with the comfyUI framework, not the standalone one.....
