### ISSUE TITLE
Installation suggestion in README to download images correctly on Ubuntu

### ISSUE THREAD

**Issue by txirrindulari** [AIGODLIKE/ComfyUI-BlenderAI-node#47]
Instead of git clone the repo on Ubuntu, it is better to do git lfs,

sudo apt-get install git-lfs; 
git lfs clone https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node.git

and for the develop branch
git lfs clone -b develop https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node.git

**Comment by KarryCharon** [comment]
lfs has been removed now.
