### ISSUE TITLE
All node greyed in latest update 

### ISSUE THREAD

**Issue by kakachiex2** [AIGODLIKE/ComfyUI-BlenderAI-node#49]
I' update the comfyui addon but wen I try to add node it appear grayed. a nd I dont get any errors.
![Screenshot 2023-12-11 150556](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/c40c9097-b62e-4503-9f42-ac173886b92f)
![Screenshot 2023-12-11 150741](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/53a5d2c1-4880-411f-b17d-65159c31d4cf)

**Comment by cx1132692358** [comment]
@kakachiex2 Update to the latest version

**Comment by KarryCharon** [comment]
@kakachiex2 You shold new a node tree first. Just like the material node
