### ISSUE TITLE
Grease pencil canvas

### ISSUE THREAD

**Issue by kakachiex2** [AIGODLIKE/ComfyUI-BlenderAI-node#50]
It's possible to use greasy pencil canvas for drawing and send it for image to image with ControlNet I'm using this PainteNode from this guy is korean and make this nice implementation but I think would be better to use grease pencil.
here are some example from node painter and my sketch from myPaint app.
![Screenshot 2023-12-07 232956](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/a5501c8f-c960-474a-952f-f54f39fa3217)
![Screenshot 2023-12-09 194006](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/ff835f1e-c58e-4b67-bc6b-b607296fae12)
![Screenshot 2023-12-11 022625](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1762112/8d3aaf3e-03f5-4f8c-b927-631283740a78)

**Comment by kakachiex2** [comment]
this is the Github for the painter node: https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet
Here is the youtube video: https://www.youtube.com/watch?v=pHGyQSr5Yj4&t=421s

**Comment by cx1132692358** [comment]
@kakachiex2 No need for such trouble, the viewport based output has already been done
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/18584564/4ce39f2c-3c83-435a-b6e6-5a97135b145d)

**Comment by kakachiex2** [comment]
Beautifull thanks great work
