### ISSUE TITLE
ComfyUI Normal Install does not run either

### ISSUE THREAD

**Issue by enzyme69** [AIGODLIKE/ComfyUI-BlenderAI-node#52]
```
DEBUG:SDN:Model Path: /Users/jimmygunawan/ComfyUI/
WARNING:SDN:Server Launching
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '0' matches no enum in 'AddonPreference', '(null)', 'cuda'
INFO:SDN:** ComfyUI start up time: 2023-12-22 06:42:59.835352
INFO:SDN:Prestartup times for custom nodes:
INFO:SDN:0.0 seconds: /Users/jimmygunawan/ComfyUI/custom_nodes/ComfyUI-Manager
INFO:SDN:Total VRAM 32768 MB, total RAM 32768 MB
INFO:SDN:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
INFO:SDN:PyTorch 2.0.0 with CUDA None (you have 2.1.0)
INFO:SDN:Python  3.10.9 (you have 3.10.13)
INFO:SDN:Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
INFO:SDN:Memory-efficient attention, SwiGLU, sparse and more won't be available.
INFO:SDN:Set XFORMERS_MORE_DETAILS=1 for more details
INFO:SDN:xformers version: 0.0.20
INFO:SDN:Traceback (most recent call last):
INFO:SDN:File "/Users/jimmygunawan/ComfyUI/comfy/model_management.py", line 214, in <module>
INFO:SDN:import accelerate
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
INFO:SDN:from .accelerator import Accelerator
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
INFO:SDN:from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
INFO:SDN:from .utils import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 159, in <module>
INFO:SDN:from .megatron_lm import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/utils/megatron_lm.py", line 32, in <module>
INFO:SDN:from transformers.modeling_outputs import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
INFO:SDN:from . import dependency_versions_check
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
INFO:SDN:require_version_core(deps[pkg])
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
INFO:SDN:return require_version(requirement, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
INFO:SDN:_compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
INFO:SDN:raise ImportError(
INFO:SDN:ImportError: huggingface-hub>=0.19.3,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.0.
INFO:SDN:Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
INFO:SDN:ERROR: LOW VRAM MODE NEEDS accelerate.
INFO:SDN:Set vram state to: DISABLED
INFO:SDN:Device: cpu
INFO:SDN:VAE dtype: torch.float32
INFO:SDN:Traceback (most recent call last):
INFO:SDN:File "/Users/jimmygunawan/ComfyUI/main.py", line 72, in <module>
INFO:SDN:import execution
INFO:SDN:File "/Users/jimmygunawan/ComfyUI/execution.py", line 12, in <module>
INFO:SDN:import nodes
INFO:SDN:File "/Users/jimmygunawan/ComfyUI/nodes.py", line 20, in <module>
INFO:SDN:import comfy.diffusers_load
INFO:SDN:File "/Users/jimmygunawan/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
INFO:SDN:import comfy.sd
INFO:SDN:File "/Users/jimmygunawan/ComfyUI/comfy/sd.py", line 12, in <module>
INFO:SDN:from . import clip_vision
INFO:SDN:File "/Users/jimmygunawan/ComfyUI/comfy/clip_vision.py", line 1, in <module>
INFO:SDN:from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, modeling_utils
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
INFO:SDN:from . import dependency_versions_check
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
INFO:SDN:require_version_core(deps[pkg])
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
INFO:SDN:return require_version(requirement, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
INFO:SDN:_compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
INFO:SDN:raise ImportError(
INFO:SDN:ImportError: huggingface-hub>=0.19.3,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.0.
INFO:SDN:Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
DEBUG:SDN:STDOUT Listen Thread Exit
ERROR:SDN:Server Launch Failed
INFO:SDN:Launch Time: 1.97s
WARNING:SDN:Parsing Node Start
WARNING:SDN:Parsing Node Finished!
INFO:SDN:ParseNode Time: 0.00s
INFO:SDN:RegNode Time: 0.01s

```

**Comment by enzyme69** [comment]
[bcomfy_002.crash.txt](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/files/13745704/bcomfy_002.crash.txt)

maybe my setting of python path is not right

**Comment by enzyme69** [comment]
Crash bad if I point into 'comfy' directory and not 'ComfyUI' directory:
INFO:SDN:UnregNode Time: 0.00s
DEBUG:SDN:Model Path: /Users/jimmygunawan/ComfyUI/comfy/
WARNING:SDN:Server Launching
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 138, in invoke
    return self.execute(context)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 142, in execute
    if res := getattr(self, self.action)():
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 377, in Launch
    self.Restart()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 410, in Restart
    TaskManager.restart_server()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 805, in restart_server
    TaskManager.run_server(fake=fake)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 769, in run_server
    run_success = TaskManager.init_server(fake=fake)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 787, in init_server
    running = TaskManager.server.run()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 575, in run
    Path(model_path).joinpath("custom_nodes", file.name).write_text(t, encoding="utf-8")
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/python/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/python/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jimmygunawan/ComfyUI/comfy/custom_nodes/cup.py'
Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 138, in invoke
    return self.execute(context)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 142, in execute
    if res := getattr(self, self.action)():
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 377, in Launch
    self.Restart()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/ops.py", line 410, in Restart
    TaskManager.restart_server()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 805, in restart_server
    TaskManager.run_server(fake=fake)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 769, in run_server
    run_success = TaskManager.init_server(fake=fake)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 787, in init_server
    running = TaskManager.server.run()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/SDNode/manager.py", line 575, in run
    Path(model_path).joinpath("custom_nodes", file.name).write_text(t, encoding="utf-8")
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/python/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/python/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jimmygunawan/ComfyUI/comfy/custom_nodes/cup.py'

WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1343 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
Writing: /var/folders/dd/6tfdfc6x5pz37mrm2msqyc9r0000gn/T/blender.crash.txt
zsh: segmentation fault  /Applications/Blender\ 36\ LTS/Blender.app/Contents/MacOS/Blender

**Comment by enzyme69** [comment]
<img width="1079" alt="Screenshot 2023-12-22 at 7 06 30 am" src="https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/3952687/d6841844-2fcd-40e7-8370-ec8d8b4bb34f">

I should change the addon path to my own install?

**Comment by enzyme69** [comment]
<img width="796" alt="Screenshot 2023-12-22 at 9 29 01 am" src="https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/3952687/44c6aa97-1cfd-428b-96af-1fa555d0df44">
I tried to fix every error, using module manager, but still not running properly in macOS...

**Comment by enzyme69** [comment]
In anyways, I can't run the server, issue:
```
INFO:SDN:UnregNode Time: 0.00s
DEBUG:SDN:Model Path: /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/
WARNING:SDN:ControlNet Init....
WARNING:SDN:ControlNet Init Finished.
WARNING:SDN:If controlnet still not worked, install manually by double clicked /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/install.bat
WARNING:SDN:Server Launching
INFO:SDN:** ComfyUI start up time: 2023-12-22 09:39:22.451163
INFO:SDN:Prestartup times for custom nodes:
INFO:SDN:0.0 seconds: /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/rgthree-comfy
INFO:SDN:0.0 seconds: /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/ComfyUI-Manager
INFO:SDN:Total VRAM 32768 MB, total RAM 32768 MB
INFO:SDN:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
INFO:SDN:PyTorch 2.0.0 with CUDA None (you have 2.1.0)
INFO:SDN:Python  3.10.9 (you have 3.10.13)
INFO:SDN:Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
INFO:SDN:Memory-efficient attention, SwiGLU, sparse and more won't be available.
INFO:SDN:Set XFORMERS_MORE_DETAILS=1 for more details
INFO:SDN:xformers version: 0.0.20
INFO:SDN:Traceback (most recent call last):
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/model_management.py", line 218, in <module>
INFO:SDN:import accelerate
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
INFO:SDN:from .accelerator import Accelerator
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
INFO:SDN:from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
INFO:SDN:from .utils import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 159, in <module>
INFO:SDN:from .megatron_lm import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/utils/megatron_lm.py", line 32, in <module>
INFO:SDN:from transformers.modeling_outputs import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
INFO:SDN:from . import dependency_versions_check
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
INFO:SDN:require_version_core(deps[pkg])
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
INFO:SDN:return require_version(requirement, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
INFO:SDN:_compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
INFO:SDN:raise ImportError(
INFO:SDN:ImportError: huggingface-hub>=0.19.3,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.0.
INFO:SDN:Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
INFO:SDN:ERROR: LOW VRAM MODE NEEDS accelerate.
INFO:SDN:Set vram state to: SHARED
INFO:SDN:Device: mps
INFO:SDN:VAE dtype: torch.float32
INFO:SDN:Traceback (most recent call last):
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/main.py", line 72, in <module>
INFO:SDN:import execution
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/execution.py", line 12, in <module>
INFO:SDN:import nodes
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/nodes.py", line 20, in <module>
INFO:SDN:import comfy.diffusers_load
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
INFO:SDN:import comfy.sd
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/sd.py", line 12, in <module>
INFO:SDN:from . import clip_vision
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/clip_vision.py", line 1, in <module>
INFO:SDN:from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, modeling_utils
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
INFO:SDN:from . import dependency_versions_check
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
INFO:SDN:require_version_core(deps[pkg])
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
INFO:SDN:return require_version(requirement, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
INFO:SDN:_compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
INFO:SDN:raise ImportError(
INFO:SDN:ImportError: huggingface-hub>=0.19.3,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.0.
INFO:SDN:Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
DEBUG:SDN:STDOUT Listen Thread Exit
ERROR:SDN:Server Launch Failed
INFO:SDN:Launch Time: 1.77s
WARNING:SDN:Parsing Node Start
WARNING:SDN:Parsing Node Finished!
INFO:SDN:ParseNode Time: 0.00s
INFO:SDN:RegNode Time: 0.05s

```

1. Do I need to install ComfyUI server path myself or your addon handles this?
2. How to set path presets?
3. How to import JSON workflows?

**Comment by cx1132692358** [comment]
@enzyme69 First, you need a COMFYUI and specify it

**Comment by cx1132692358** [comment]
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/18584564/abb4fe18-706f-4711-af2b-be2df254b848)
