### ISSUE TITLE
this addon would be godlike IF it had blender nodegroups.

### ISSUE THREAD

**Issue by Ulf3000** [AIGODLIKE/ComfyUI-BlenderAI-node#55]
With that i mean: collapsable nodegroups **with group input node and group out put node** !

![grafik](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/10765339/e4676372-5d8c-46c7-b129-2db7cdf50b76)

Yeah just imagine ... we could easily build a superworkflow , expose the important parameters to the nodegroups ui and enable and disable them just like comfy native , everything clean with a minimal perfect ui ... it would be the rule them all ui for stable diffusion.

i know this would mean saving the workflows in another format but we can easily just save **ALL** workflows in one blender file 🤷‍♂️🤷‍♂️🤷‍♂️.
no need to export .. we would just need a good importer for downloaded workflows.

**Comment by Yorha4D** [comment]
@Ulf3000 Great idea, currently trying it out because Blender and ComfyUI have different groups

**Comment by Ulf3000** [comment]
> @Ulf3000 Great idea, currently trying it out because Blender and ComfyUI have different groups

yes it will need to be saved into its own blender format i guess. But like mentioned , in blender comfyui is more powerful than in the browser. you can save basically all workflows that you ever used right in the blender file. 
![grafik](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/10765339/08b61ad9-8696-4a5a-a8ed-4d9c907dda0e)

**Comment by Yorha4D** [comment]
@Ulf3000 
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/116185401/bc96d8f2-d962-4ea2-a67e-9bfe5b0b304e)
Currently, a version has been implemented, but it is still very primitive. In fact, packaging into groups is much more challenging than imagined, and it may take several weeks to see a stable version. (Blender itself does not support third-party grouping very well, we need to write code to implement it.)

**Comment by Ulf3000** [comment]
damn , exactly like that. im excited what you come up with!

**Comment by KarryCharon** [comment]
@Ulf3000 Packing group feature enabled now. Have fun!

**Comment by Ulf3000** [comment]
exactly like that ! awesome. i could reduce the number of nodes by over 50% in the test workflow (complicated workflow with several controlnets and faceid )
