### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by Xenodimensional** [AIGODLIKE/ComfyUI-BlenderAI-node#57]
Comfy starts but the output window says **Read timed out**? Windows 10, Blender 3.6.

![meh](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/66627464/bec4559a-7bc4-4b72-90d3-1474ec30c32c)

**Comment by cx1132692358** [comment]
@Xenodimensional This may be because the port is occupied，You can try using other ports, such as 8000
