### ISSUE TITLE
Addon enabling error

### ISSUE THREAD

**Issue by newillusion** [AIGODLIKE/ComfyUI-BlenderAI-node#59]
On Blender 3.6.5, when i try to enable addon (to check in the empty square), error message displayed:
![BlenderAI_Node (error on windows7)](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/13040758/06eb499b-d582-4dc0-8b8e-c991d9142fb4)

_File "C:\Users\....\Blender\3.6\scripts\addons\BlenderAI_Node\External\lupawrapper.py", line 133> in load_dll_

  _if dll_name in self.dll:_

_AttributeError: 'LuaRuntime' object has no attribute 'dll'_

**Comment by KarryCharon** [comment]
@newillusion Open the blender console and upload all of log info, which can be helpful.

**Comment by BenderBlender** [comment]
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/116355906/b1be3139-aba4-49ae-a315-eab6f3d3d333)
It also fails to start, the blender throws an error

**Comment by KarryCharon** [comment]
@newillusion Fixed now, try the latest dev version

**Comment by BenderBlender** [comment]
Reinstallation comfyui helped me for this problem
