### ISSUE TITLE
In Blender 3.6, Input Image node and preview node undefined.

### ISSUE THREAD

**Issue by Bikimaharjan** [AIGODLIKE/ComfyUI-BlenderAI-node#62]
"Undefined node > Input image",  "Undefined node > Preview"

**Comment by KarryCharon** [comment]
@Bikimaharjan Click `Launch/Connet ComfyUI` button first, then load workflow

**Comment by Bikimaharjan** [comment]
I did launch comfy Ui first. Even though it is showing undefined node.

**Comment by KarryCharon** [comment]
@Bikimaharjan Can you upload the console log? Maybe there are some bugs :)

**Comment by Bikimaharjan** [comment]
I did not use it yesterday. Today I tried It is showing now.
