### ISSUE TITLE
在本地macbook链接远程win的comfyUI server这种工作方式会有很多问题

### ISSUE THREAD

**Issue by robtl2** [AIGODLIKE/ComfyUI-BlenderAI-node#69]
1. 找不到input image这个直接获取blender视口作为图像的节点
2. 不能预览生成的图像，总之你们视频教程里专门给blender写的节点都找不到
3. 建议连远程comfyUI服务可以保存生成图像到本地

总结下我的使用体验，如果我直接在win的高配电脑下使用blender与comfyUI合作的话，那其实没有多大的必要使用这个工具，因为mixlab里有相关的截屏工具已经很方便了。但如果是像我这种想躺床上用mac电脑就能舒服的链接win的高配电脑工作的话，那现在上面三个问题就会挡在路上。
 
最后，感谢你们热情的工作！

**Comment by Yorha4D** [comment]
@robtl2 
= =、如果不会用去看教程，找不到节点可以用搜索，开发就是在mac开发的。不知道为什么你会遇到这些问题，刚才又专门测试了一遍，这令人费解。最后感谢你的反馈。
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/116185401/9e29b4ef-2dbc-46ae-b36c-8e0dda4ef2b5)
