### ISSUE TITLE
Does anyone know the installation path of the plugin under Mac?

### ISSUE THREAD

**Issue by junne14105** [AIGODLIKE/ComfyUI-BlenderAI-node#71]
After reading the tutorials, they are all win's. I don't know where the path address is under Mac!

**Comment by KarryCharon** [comment]
@junne14105 You should prepare the python env with macOS(set the python interpreter path of BlenderAI_Node addon). And then everything will work fine on it.

**Comment by KarryCharon** [comment]
And for the title, you can check the `/Users/your_login_name/Library/Application Support/Blender/your_blender_version/scripts/addons` for addon installation.
