### ISSUE TITLE
Can't find Blender nodes

### ISSUE THREAD

**Issue by RobeSantoro** [AIGODLIKE/ComfyUI-BlenderAI-node#74]
I'm trying to integrate Blender camera render as input for ControlNet.
I cannot find any node that could do that. Am I missing something?

I'm looking for a node called 'Input' that I can see in some screenshots from the readme:

![https://raw.githubusercontent.com/AIGODLIKE/ComfyUI-BlenderAI-node/main/.img/a5eac30ddffa1602c37aaee94cc9cf1ab2d8345f5fd59b7dc1ebd24954ea0d1b.jpg](https://raw.githubusercontent.com/AIGODLIKE/ComfyUI-BlenderAI-node/main/.img/a5eac30ddffa1602c37aaee94cc9cf1ab2d8345f5fd59b7dc1ebd24954ea0d1b.jpg)

This one [here](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/blob/main/README_EN.md#blender)

If I open a workflow with that feature, that node is missing.
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/1170571/4c6c009a-53b0-4120-8f8a-ee8cc3dce4bd)

What am I doing wrong?

**Comment by RobeSantoro** [comment]
I just figured out that my https://github.com/AIGODLIKE/ComfyUI-CUP had some issues while cloning; I just deleted it and git cloning again, and now everything works.

**Comment by Yorha4D** [comment]
> I just figured out that my https://github.com/AIGODLIKE/ComfyUI-CUP had some issues while cloning; I just deleted it and git cloning again, and now everything works.

@RobeSantoro Hi, I think this issue is caused by installing ComfyUI or Blender 4.1 to upgrade the Python library
https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/releases/tag/V1.49

**Comment by mcrimson974** [comment]
> @RobeSantoro Hi, I think this error is caused by installing ComfyUI or Blender 4.1 to upgrade the Python library https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/releases/tag/V1.49

I tried to download the zip from the link you sent. I installed it in blender 4.1. I added Python 3.11 path in the "Python Path" field but I get this error below. (I also tried with adding Python 3.10 path instead of 3.11, I still get the same error).

```
Python: Traceback (most recent call last):
  File "C:\Users\max\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderAI_Node\ops.py", line 770, in execute
    bpy.ops.node.translate_attach("INVOKE_DEFAULT")
  File "D:\0_softwares\Blender4.1\4.1\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.node.translate_attach.poll() failed, context is incorrect
```
