### ISSUE TITLE
Blender Nodes Diseappear when launching server (Blender 4.1)

### ISSUE THREAD

**Issue by gioxyer** [AIGODLIKE/ComfyUI-BlenderAI-node#81]
Version used: ComfyUI Blender 1.4.9
System info: Windows 11 Home
CPU : Ryzen 5 5500U with Radeon Vega 7 Graphics Card
ComfyUI : CPU mode

Blender Nodes Diseappear when launching server (Blender 4.1):
- when server isn't loading Blender Nodes appear
- when loading server Blender Nodes diseapper

Video about the error:
https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/7a90fbe4-25de-4eba-a359-6a1cfd497b96

Link of Blender file:
[https://we.tl/t-LP85nWpYML](https://we.tl/t-LP85nWpYML?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

**Comment by mcrimson974** [comment]
Same problem here. This is the MOST important thing to fix. Otherwise the whole addon becomes pointless. I might as well just use Comfy UI instead.
(Using blender 4.0)

**Comment by gioxyer** [comment]
Thanks for suggestion, which version do you use in Blender 4.0 for ComfyUI?

**Comment by mcrimson974** [comment]
> Thanks for suggestion, which version do you use in Blender 4.0 for ComfyUI?

My version of ComfyUI is master@30abc32

**Comment by gioxyer** [comment]
And for this AddOn which version do you have?

**Comment by mcrimson974** [comment]
> And for this AddOn which version do you have?

I have the latest, 1.4.9. I also tried on 1.4.8 but same thing.

Also, I've tried again since then, and I don't know why but I can't event add the input image node to the graph, even before launching the server. I get this error : 

`Python: Traceback (most recent call last):
  File "C:\Users\max\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderAI_Node\ops.py", line 770, in execute
    bpy.ops.node.translate_attach("INVOKE_DEFAULT")
  File "D:\0_softwares\Blender4.1\4.1\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.node.translate_attach.poll() failed, context is incorrect`

**Comment by gioxyer** [comment]
Did you try also with Blender 3.6?

**Comment by KarryCharon** [comment]
@gioxyer 

> Version used: ComfyUI Blender 1.4.9 System info: Windows 11 Home CPU : Ryzen 5 5500U with Radeon Vega 7 Graphics Card ComfyUI : CPU mode
> 
> Blender Nodes Diseappear when launching server (Blender 4.1):
> 
> * when server isn't loading Blender Nodes appear
> * when loading server Blender Nodes diseapper
> 
> Video about the error: https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/7a90fbe4-25de-4eba-a359-6a1cfd497b96
> 
> Link of Blender file: [https://we.tl/t-LP85nWpYML](https://we.tl/t-LP85nWpYML?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

Try the develop branch for testing. And some console log is needed. Thanks!

**Comment by gioxyer** [comment]
Do you mean version 1.5.0 from zip archive? 

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/180187d8-9fd7-4a49-941c-601a29560f4e)

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/ac2332ee-b8da-482e-91ff-3696ca8b1e2c)

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/07f45ab6-8bb6-4ab0-aa5e-169493f1c016)

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/a0911480-55b0-48b1-8b2d-3cb3b6470cd3)

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/484ddde4-0291-4f25-82b4-f7ba6d1fb509)

WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'CheckpointLoaderSimple', 'CheckpointLoaderSimple', 'ckpt_name'

**Comment by KarryCharon** [comment]
> Do you mean version 1.5.0 from zip archive?
> 
> ![image](https://private-user-images.githubusercontent.com/161426313/323865617-180187d8-9fd7-4a49-941c-601a29560f4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYyMDUsIm5iZiI6MTcxMzUxNTkwNSwicGF0aCI6Ii8xNjE0MjYzMTMvMzIzODY1NjE3LTE4MDE4N2Q4LTlmZDctNGE0OS05NDFjLTYwMWEyOTU2MGY0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwODM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGRmZTc4ZmRhNjYyZDAwMjk4YmU4NmIxMGFhYzQ5MTI3NzQ3NDZhZjEzZjExNjY5NTEzZjc1ODg0OTg5NTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pQx16iYManleiuLmisW_0tseBjBDsRAeTgxFZpsYryE)
> 
> ![image](https://private-user-images.githubusercontent.com/161426313/323865763-ac2332ee-b8da-482e-91ff-3696ca8b1e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYyMDUsIm5iZiI6MTcxMzUxNTkwNSwicGF0aCI6Ii8xNjE0MjYzMTMvMzIzODY1NzYzLWFjMjMzMmVlLWI4ZGEtNDgyZS05MWZmLTM2OTZjYThiMWUyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwODM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2Y4MWJmODA5MDFhYTIzNTM3YzRhYWUzZDFlMDQ2ZGQyODgwYmQ3ZGFjMzcwMjVhNTc0ZTRjNzc1YjdlNWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hwv9PQJ-zB_dARZDJsxC-sVHDZqfYhvNRU2PhQh2XdE)
> 
> ![image](https://private-user-images.githubusercontent.com/161426313/323865917-07f45ab6-8bb6-4ab0-aa5e-169493f1c016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYyMDUsIm5iZiI6MTcxMzUxNTkwNSwicGF0aCI6Ii8xNjE0MjYzMTMvMzIzODY1OTE3LTA3ZjQ1YWI2LThiYjYtNGFiMC1hYTVlLTE2OTQ5M2YxYzAxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwODM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjIwZGQzNjM3ZmFhMjJmM2U0ZTU2Y2YzYTM0NTVmNDhkNjdmZjExNmIzMDE1NjFhYmZlMzcxZWRiZTBhOTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aUU2Y4CFRNm2W61GuD32ROUWmBiZPbMOkrJWvJxhQuA)
> 
> ![image](https://private-user-images.githubusercontent.com/161426313/323866281-a0911480-55b0-48b1-8b2d-3cb3b6470cd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYyMDUsIm5iZiI6MTcxMzUxNTkwNSwicGF0aCI6Ii8xNjE0MjYzMTMvMzIzODY2MjgxLWEwOTExNDgwLTU1YjAtNDhiMS04YjJkLTNjYjNiNjQ3MGNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwODM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDEwZDNiMjg2MGY0NGVhYjc3NTAxNWUwYWZiM2QzMDRkZWM3OGRkMzUwM2NiZTQ0MTI2NzJjNzk4ZTQ5ZmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nWCV45mjk0TIRbL3Ed-g2WjuZGx3dteaOWTGUy3uMMs)
> 
> ![image](https://private-user-images.githubusercontent.com/161426313/323866776-484ddde4-0291-4f25-82b4-f7ba6d1fb509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYyMDUsIm5iZiI6MTcxMzUxNTkwNSwicGF0aCI6Ii8xNjE0MjYzMTMvMzIzODY2Nzc2LTQ4NGRkZGU0LTAyOTEtNGYyNS04MmI0LWY3YmE2ZDFmYjUwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwODM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmE3YjJkZTdlYmI3ZTJhYTNhMTAwNGQ3YWE3ZDJiNTI0Yzk1NWVhYThjODhmN2ZhODE0MDQxZmY0YmI5NGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E9gi6qV8ArabQ1-BtOzy3M5b-4txxwJ_iLLcmuKxa2A)
> 
> WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'CheckpointLoaderSimple', 'CheckpointLoaderSimple', 'ckpt_name'
This warning info is caused by the CheckpointLoaderSimple model is not set.

**Comment by gioxyer** [comment]
I add a model, it doesn't show the error, but the problem still persist of Blender menu diseapper 
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/da4d1a26-edc2-475a-9e13-1911387d9e43)

[SDN-INF]: Load MLT Words: 0.7354s
[SDN-WRN]: Server Launched
[SDN-INF]: Launch Time: 0.04s
[SDN-INF]: UnregNode Time: 0.00s
register_class(...):
Warning: 'MLTWords_UL_UIList' doesn't have upper case alpha-numeric prefix
register_class(...):
Warning: 'MLTText_UL_UIList' doesn't have upper case alpha-numeric prefix
[SDN-WRN]: Parsing Node Start
[SDN-WRN]: Parsing Node Finished!
[SDN-INF]: ParseNode Time: 0.06s
[SDN-INF]: RegNode Time: 0.18s

**Comment by gioxyer** [comment]
Blender info log 
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/d46a1d7d-0315-4f97-8adc-ac865fe9827c)

**Comment by KarryCharon** [comment]
@gioxyer Copy log from blender console instead of the info window.

**Comment by KarryCharon** [comment]
@mcrimson974 Header Menu [Window] -> Toggle System Console

**Comment by gioxyer** [comment]
Error: ('Invalid Node Type: Þ¥ôÕàÑÕø¥ÕâÅ',)

[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 54, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 233, in serialize
    self.validation()
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 248, in validation
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(n.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

[SDN-ERR]: Invalid Node Type: 输入图像
[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 71, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 397, in save_json_ex
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(from_socket.node.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

Error: ('Invalid Node Type: Þ¥ôÕàÑÕø¥ÕâÅ',)

[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 54, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 233, in serialize
    self.validation()
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 248, in validation
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(n.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/ab0e4dec-1d8b-4d1a-8d0b-a5ee578dd8b1)

**Comment by gioxyer** [comment]
Full session:
[SDN-INF]: Load MLT Words: 0.7354s
[SDN-WRN]: Server Launched
[SDN-INF]: Launch Time: 0.04s
[SDN-INF]: UnregNode Time: 0.00s
register_class(...):
Warning: 'MLTWords_UL_UIList' doesn't have upper case alpha-numeric prefix
register_class(...):
Warning: 'MLTText_UL_UIList' doesn't have upper case alpha-numeric prefix
[SDN-WRN]: Parsing Node Start
[SDN-WRN]: Parsing Node Finished!
[SDN-INF]: ParseNode Time: 0.06s
[SDN-INF]: RegNode Time: 0.18s
[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 54, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 233, in serialize
    self.validation()
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 248, in validation
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(n.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

[SDN-ERR]: Invalid Node Type: 输入图像
[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 71, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 397, in save_json_ex
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(from_socket.node.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

Error: ('Invalid Node Type: Þ¥ôÕàÑÕø¥ÕâÅ',)

[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 54, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 233, in serialize
    self.validation()
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 248, in validation
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(n.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

[SDN-ERR]: Invalid Node Type: 输入图像
[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 71, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 397, in save_json_ex
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(from_socket.node.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

Error: ('Invalid Node Type: Þ¥ôÕàÑÕø¥ÕâÅ',)

[SDN-ERR]: Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 54, in wrapper
    res = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 233, in serialize
    self.validation()
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5\SDNode\tree.py", line 248, in validation
    raise InvalidNodeType(_T("Invalid Node Type: {}").format(n.name))
ComfyUI-BlenderAI-node-919ae8a3e4c9c4dfd72e3ae0c77dc03db12811a5.SDNode.tree.InvalidNodeType: Invalid Node Type: 输入图像

**Comment by KarryCharon** [comment]
@gioxyer 
You can try select log from the start of Blender launching

**Comment by gioxyer** [comment]
Do you mean blender_debug_log?

**Comment by KarryCharon** [comment]
> Do you mean blender_debug_log?

Yes if you know how

**Comment by gioxyer** [comment]
Do you mean from cmd? I have only .cmd or should I create .bat from scratch?
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/845bfd86-f282-41de-adac-fdde483de7b0)

**Comment by gioxyer** [comment]
And which one do you need before I used debug_log, do you need debug_gpu?

**Comment by KarryCharon** [comment]
> And which one do you need before I used debug_log, do you need debug_gpu?

blender_debug_log.cmd

**Comment by gioxyer** [comment]
[blender_debug_output.txt](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/files/15040226/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/files/15040227/blender_system_info.txt)

**Comment by gioxyer** [comment]
Quit.blend file:
https://we.tl/t-vRIZwiNWXM

**Comment by KarryCharon** [comment]
> [blender_debug_output.txt](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/files/15040226/blender_debug_output.txt) [blender_system_info.txt](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/files/15040227/blender_system_info.txt)

it's weird... There is no error find inside this log file.

**Comment by KarryCharon** [comment]
> Quit.blend file: https://we.tl/t-vRIZwiNWXM

Are you used some software like toDesk or teamviewer?

**Comment by KarryCharon** [comment]
> Warning: 'MLTWords_UL_UIList' doesn't have upper case alpha-numeric prefix , this one is from ComfyUI?

Just a warning. No influence about the title

**Comment by gioxyer** [comment]
I could record a clip to share what happen if you want

**Comment by KarryCharon** [comment]
> I could record a clip to share what happen if you want

If it's convenient, I can help you debug it through remote desktop

**Comment by gioxyer** [comment]
Do you have an email where can I contact you?

**Comment by KarryCharon** [comment]
> Do you have an email where can I contact you?

tangpeng124@gmail.com

**Comment by gioxyer** [comment]
@mcrimson974 we find a solution you need to install : https://github.com/AIGODLIKE/ComfyUI-CUP inside ComfyUI folder as unzip file

**Comment by mcrimson974** [comment]
> @mcrimson974 we find a solution you need to install : https://github.com/AIGODLIKE/ComfyUI-CUP inside ComfyUI folder as unzip file

@gioxyer This is not a solution actually, it was already installed in my ComfyUI/custom_nodes folder when I wrote my comment.

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/46675520/8872af24-6905-4ce2-9764-2fa0d63dd271)


Can you please tell me guys what version of blender, and addon as well as ComfyUI-CUP you're running? 
Maybe make a small video tutorial for installing them and showing that it's all running fine would help a ton!
Thank!

**Comment by gioxyer** [comment]
@mcrimson974 If I just tested also Control NET with open pose model is working, I use the correction version as beta 1.5.0, I didn't try the Blender version corrective 1.4.9, if you want I could try that version and make a tutorial

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/493886b0-eeb7-4fa8-995e-b67c8bf99132)

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/bcd81055-d16e-493e-b1be-3a6040ea4a32)

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/90bed966-55e1-442a-a6e9-ddb5c535362c)

**Comment by gioxyer** [comment]
It works also with the last corrective version 1.4.9, make sure to set the path correctly on local server
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/34738a6f-8927-4645-85a5-0f3350650e5b)
