### ISSUE TITLE
Input Image Node translation

### ISSUE THREAD

**Issue by 974test** [AIGODLIKE/ComfyUI-BlenderAI-node#83]
It seems like you forgot to translate the buttons of the Input Image node  in English: 
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/107752126/5481f17e-2bca-4492-bc07-969b36ff00d4)

I think it should be : 
Input
Render
Sequence
Viewport

**Comment by KarryCharon** [comment]
@974test Fixed now. Try develop branch
