### ISSUE TITLE
ALEK 节点无法使用

### ISSUE THREAD

**Issue by QIMINGZITAINANL** [AIGODLIKE/ComfyUI-BlenderAI-node#87]
alek节点在Web UI可以使用，在BLENDER里面无法使用

**Comment by KarryCharon** [comment]
> alek节点在Web UI可以使用，在BLENDER里面无法使用

具体指的是什么呢? 可以提供一个测试工作流吗?

**Comment by sevive** [comment]
alek中的DeepTranslatorCLIPTextEncodeNode和DeepTranslatorTextNode在Blender中无法识别，控制台输出：
[SDN-ERR]: -------------------------------------------------------------------------------------------------------------
[SDN-ERR]: 错误枚举: unhashable type: 'list'
[SDN-ERR]: 节点名称: DeepTranslatorCLIPTextEncodeNode
[SDN-ERR]: 输入项名: add_proxies
[SDN-ERR]: 输入类型: ENUM
[SDN-ERR]: 输入项值: [[True, False]]
[SDN-ERR]: -------------------------------------------------------------------------------------------------------------
[SDN-WRN]: 跳过解析节点: DeepTranslatorCLIPTextEncodeNode
[SDN-ERR]: -------------------------------------------------------------------------------------------------------------
[SDN-ERR]: 错误枚举: unhashable type: 'list'
[SDN-ERR]: 节点名称: DeepTranslatorTextNode
[SDN-ERR]: 输入项名: add_proxies
[SDN-ERR]: 输入类型: ENUM
[SDN-ERR]: 输入项值: [[True, False]]
[SDN-ERR]: -------------------------------------------------------------------------------------------------------------
[SDN-WRN]: 跳过解析节点: DeepTranslatorTextNode
