### ISSUE TITLE
No Live Previews During Generation

### ISSUE THREAD

**Issue by hdworkstation103** [AIGODLIKE/ComfyUI-BlenderAI-node#89]
Hello!

Thank you for your hard work.

**Issue Description:**
- **Problem:** No live previews are appearing inside of Blender's interface during generation.
- **Blender Version:** 4.0
- **Samplers Tested:** 
  - KSampler (Efficient)
  - Ksampler Fooocus
- **ComfyUI Version:** Latest (portable, recently updated)

**Additional Details:**
I've read through the README.md multiple times. Although there is no explicit mention of the ability to view preview images within Blender during generation, there are options to enable it from within the addon's UI configuration. Previews, however, do work within the ComfyUI web interface.

**Attempted Solutions:**
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/126386057/324ec9db-0260-46c9-a615-d4ffadee6221)

**Request:**

**Feature Inquiry:**  
Is the live preview during generation a feature that is currently being developed or planned for future updates? If this feature is under active development or is scheduled for implementation, please let me know, and feel free to close this issue as I eagerly await its release.

**Documentation Suggestion:**  
If the live preview feature is intended to work only within the ComfyUI web interface and not directly in Blender, I suggest updating the README.md to clearly state this. This clarification would help prevent confusion for other users who might also be expecting in-Blender previews based on the UI configuration options available.

**Comment by KarryCharon** [comment]
@hdworkstation103 WIP

**Comment by KarryCharon** [comment]
@hdworkstation103 Done. Try develop branch for this new feat.

**Comment by hdworkstation103** [comment]
> @hdworkstation103 Done. Try develop branch for this new feat.

Thank you very much, I will give it a try. :)
